version: "3.8"

services:
  db:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    volumes:
      - ./log:/home/app/depot/log
    env_file:
      - .env
    ports:
      - "8001:80"
    depends_on:
      - db

volumes:
  pgdata:
