version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  chrome:
    image: selenium/standalone-chrome:4.19.1-20240402
    shm_size: 2gb
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

